### ISSUE TITLE
Run-or-raise on floating windows

### ISSUE THREAD

**Issue by idr4n** [holgerschurig/dotfiles#1]
Thanks a lot for the script to run-or-raise applications in Sway. It works quite well.

In my case at least, however, it does not work if an application is on floating mode. Basically instead of raising it, it opens a new instance. Could there be a way to make it work so it also detects apps in floating mode.

Thanks in advance!

**Comment by holgerschurig** [comment]
Hi,

you need to look at the JSON returned from Sway and modify how it is parsed.

I rarely use floating windows, so this never occured to me.

Greetings  Holger

Ivan Duran ***@***.***> schrieb am Do., 8. Juni 2023, 20:16:

**Comment by idr4n** [comment]
Great, thanks for pointing me in the right direction. Will do as suggested.
